version: '3.4'
services:
    mariadb:
      image: docker.io/bitnami/mariadb:10.6
      container_name: stdm_mariadb
      ports:
        - 3306:3306
      networks:
          - stdm_net
      environment:
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_USER=maria
        - MARIADB_PASSWORD=maria
        - MARIADB_DATABASE=bitnami_moodle
        - MARIADB_CHARACTER_SET=utf8mb4
        - MARIADB_COLLATE=utf8mb4_unicode_ci
      volumes:
        - 'mariadb_data:/bitnami/mariadb'
      healthcheck:
        test: mysql -u root --password=root -e"CREATE DATABASE IF NOT EXISTS study_manager"
        start_period: 5s
        interval: 5s
        timeout: 5s
        retries: 55
    app:
      image: stdm_app
      build:
        context: .
        dockerfile: AppDockerfile
      container_name: stdm_app
      ports:
        - 3000:3000
        - 5000:5000
      networks:
          - stdm_net
      depends_on:
        mariadb:
          condition: service_healthy
      command: >
        bash -c "npx sequelize-cli db:migrate
        && npx sequelize-cli db:seed:all
        && npm run docker"
    moodle:
      image: docker.io/bitnami/moodle:4
      container_name: stdm_moodle
      networks:
          - stdm_net
      ports:
        - '80:8080'
        - '443:8443'
      environment:
        - MOODLE_DATABASE_HOST=mariadb
        - MOODLE_DATABASE_PORT_NUMBER=3306
        - MOODLE_DATABASE_USER=maria
        - MOODLE_DATABASE_PASSWORD=maria
        - MOODLE_DATABASE_NAME=bitnami_moodle
        - MOODLE_USERNAME=user
        - MOODLE_PASSWORD=bitnami
      volumes:
        - 'moodle_data:/bitnami/moodle'
        - 'moodledata_data:/bitnami/moodledata'
      depends_on:
        mariadb:
          condition: service_healthy
    sync_users:
      image: stdm_moodle-box
      build:
        context: .
        dockerfile: BoxDockerfile
      container_name: sync_users
      networks:
        - stdm_net
      depends_on:
        mariadb:
          condition: service_healthy
      command: >
        bash -c "node index.js sync_users"
    sync_tasks:
      image: stdm_moodle-box
      build:
        context: .
        dockerfile: BoxDockerfile
      container_name: sync_tasks
      networks:
        - stdm_net
      depends_on:
        mariadb:
          condition: service_healthy
      command: >
        bash -c "node index.js sync_tasks"
networks:
    stdm_net:
volumes:
    mariadb_data:
      driver: local
    moodle_data:
      driver: local
    moodledata_data:
      driver: local